# Samples and populations

If you wanted to know the heights of all the people in your family, you could measure each person and make a data table with each person's name and height. This table would represent your entire "population" of interest (your family) and you would not need any statistics for that.  

Most of the time, however, we are interested in much larger populations, such as all the people in a country, or all the trees in a forest. Measuring every individual in these populations is usually not feasible, so instead we take a smaller *sample* from the population and use statistics to make *inferences* about the entire population based on that sample. Statistics bridges the gap between the sample we are able to measure, and the much larger population we are interested in.  

When we measure the heights of the people in our sample, it is not because we are only interested in those specific people, but because we want to use that information to make statements about the heights of all the people in the *population of interest*. The population of interest is some group of people that we want to learn about - it can be all the people in a country, or all the people with a certain disease. The sample is a smaller group of people that we actually measure, and who represent the larger population. For this reason, they should actually be selected very carefully, because they must truly *represent* (be silimar enough to) the larger population we want to learn about.  

Once we have measured our sample, we usually summarise the data we gathered, for example by calculating the average height of the people in our sample. This summary statistic (the average height) is then used as a starting point for *estimating* what the true average height of the entire population might be. Because our sample is only a small part of the entire population, our *estimate* of the population average will not be exact, but will have some *uncertainty* associated with it. It should be quite intuitive as well that, the more people we measure in our sample, the more accurate our estimate of the population average will be. The size of the sample is therefore many times a decision between the resources we have available (time, money, effort) and the accuracy we want to achieve. 

We don't just take the sample average as the population average, as is. We use both the average and the average variation across the different individuals in our sample to estimate the population average and its variability (uncertainty or error).  To do this, we use the principles of *probability theory* and what we have learned over many hundreds of years about measuring things and how those measurements tend to be *distributed* across a range of possible values. This is how statistical methods have been developed - finding ways to estimate the true population characteristics, based on measuring sample characteristics in a relatively small number of individuals. The way statistical methods have been developed also ensures that we can *quantify the uncertainty* in our estimates, always reminding ourselves that we are *estimating*, not actually *measuring* the true population characteristics.    

