# Where does data come from?

It is not hard to agree that we live in an "everything is data" age. Even so, it still needs to be measured and captured to be useful for analysis. In some cases, this can be very easy and cheap, but other times it needs careful planning and expensive equipment. To do data analysis, you do need to understand where data comes from, how it is collected, and what limitations it might have. It is not appropriate to analyse and come to conclusions about a system, using data that just happened to be available, but which doesn't really measure exactly the thing which you are making conclusions about. A simple example of this may be using data available for one country, to make conclusions about another country, which may have very different characteristics. Our task as researchers therefore is not just about taking whichever data we obtain, or generate at face value, but to think critically about how bias may have been introduced and how this may affect our conclusions.  