# Why statistics?

Human beings have been counting things for a long time. At some point, we realized that counting alone was not enough; we needed ways to summarize, analyze, and make sense of the data we collected. This realization led to the development of statistics as a formal discipline. We started using statistics for all sorts of things, from taking serious decisions to playing games. We gamble, follow sports, test the effectiveness of medicine and trace our own ancestry using statistics. We use it to understand systems and processes that can be measured, and many times, to predict how those systems and processes will behave in the future.  

As with many things, statistics can be misused. People have used data to deliberately misrepresent the truth of a situation, or sometimes they have just done a poor job of handling it, and messed up their conclusions because of incompetence. Either way, anyone in science and research needs to have an understanding of the basic concepts of statistics, to be able to handle data responsibly and reproducibly.  

We also have seen a transformation in data analysis, brought about by the availability of computing power, that could scarcely be imagined a few decades ago. Although many traditional statistical methods are still very useful, we now have access to a whole new set of techniques that can handle large and complex datasets, like machine learning and large language models. Even though these methods are new, and sometimes not transparent in how they work, they are still based on fundemental principles like probability theory, randomness and inference.  Maybe especially because of the complexity and lack of transparency in some of these methods, it is important to have a solid understanding of the basics of statistics, to be able to critically evaluate the results they produce.  